name: critique-test
on:
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: ./critique
jobs:
  critique-test:
    environment:
      name: critique-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stacked
        uses: actions/checkout@v5
      - name: Configure critique
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
      - name: Install critique
        run: npm ci
      - name: Build critique
        run: npm run build --if-present
      # lists build outputs - remove after deploy tests
      - name: List pwd
        run: pwd
      - name: List wd
        run: ls -l ./
      - name: List output
        run: ls -l ./out
      - name: List critique
        run: ls -l ./critique/out
      # ^^^
      - name: Test critique
        run: npm test
