# critque-test action
name: critique-test
on:
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: ./critique
jobs:
  test:
    environment:
      name: critique-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout stacked
        uses: actions/checkout@v5
      - name: Configure critique
        uses: actions/setup-node@v4
        with:
          node_version: '22.17.0'
      - name: install critique
        run: npm ci
      - name: build critique
        run: npm run build --if-present
      - name: test critique
        run: npm test
