# critque-test action
name: critique-test
on:
  pull_request:
    branches:
      - main
jobs:
  environment: CRITIQUE-TEST
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout critique
        uses: actions/checkout@v5
      - name: Configure critique
        uses: actions/setup-node@v4
        with: '22.17.0'
      - name: Install critique
        run: npm ci
      - name: Build critique
        run: npm run build --if-present
      - name: Test critique
        run: npm test
